### ISSUE TITLE
Fails with run time error: 'TypeError: sequence item 0: expected str instance, bytes found'

### ISSUE THREAD

**Issue by frankdeepl** [svpino/tf_object_detection_cm#2] opened 2018-11-13 02:18 UTC
Hi Svpino,

When I tired to run your code on my dataset, I faced this problem. 
Do you know how to resolve this problem?  

`Traceback (most recent call last):
  File "confusion_matrix.py", line 151, in <module>
    tf.app.run(main)
  File "/home/dongs/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "confusion_matrix.py", line 146, in main
    confusion_matrix = process_detections(FLAGS.detections_record, categories)
  File "confusion_matrix.py", line 62, in process_detections
    decoded_dict = data_parser.parse(example)
  File "/home/dongs/Documents/Project/object-detection-tool/object-detection-tool-debug/models/research/object_detection/metrics/tf_example_parser.py", line 153, in parse
    results_dict[key] = parser.parse(tf_example)
  File "/home/dongs/Documents/Project/object-detection-tool/object-detection-tool-debug/models/research/object_detection/metrics/tf_example_parser.py", line 49, in parse
    self.field_name].HasField("bytes_list") else None
TypeError: sequence item 0: expected str instance, bytes found
`

Thanks.

**Comment by svpino** [comment] 2018-11-14 16:34
Hi there, this is a duplicate of issue #1. Take a look at that one for the solution.

**Closed as completed** 2018-11-14 16:34 UTC
